net:
  DBPN_3:
    scale_factor: 4
    num_channels: 3
    base_filter: 96
    feat: 96
    num_stages: 3
    residual: true
save_dir: ./output/dbpn_4x
trainer:
  SISRTrainer:
    epochs: 200
    log_dir: logs
    ckpt_dir: ckpt
    log_frq: 10
    output_dir: ./output/dbpn_4x/05-30-10/eval
    restore_ckpt: ./output/dbpn_4x/05-30-10/ckpt/model-epoch157.pth.tar
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.0001
scheduler:
  name: none
data:
  name: SISRDataset
  test:
    image_dir: ./data
    upscale_factor: 4
    sample_stride: 64
    data_argumentation: false
    file_list: ./data/test_sisr.txt
    keep_full: true
    patch_size: [64, 64]
    batch_size: 16
    shuffle: false
    num_workers: 4
    repeat: 1
    mod: 1