net:
  DBPN_3:
    scale_factor: 4
    num_channels: 3
    base_filter: 32
    feat: 64
    num_stages: 3
    residual: true
save_dir: ./output/dbpn_4x
trainer:
  SISRTrainer:
    epochs: 100
    log_dir: logs
    ckpt_dir: ckpt
    log_frq: 10
    restore_ckpt: ckpt/model-best-pth.tar
    gradient_loss_weight: 1.0
    clip_grad: 2.5
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.0001
scheduler:
  name: MultiStepLR
  gamma: 0.1
  milestones: [40, 80]
data:
  train:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    data_argumentation: true
    file_list: ./data/train_sisr.txt
    patch_size: [64, 64]
    batch_size: 32
    shuffle: true
    num_workers: 8
    repeat: 5
    mod: 1
  val:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/val_sisr.txt
    patch_size: [64, 64]
    batch_size: 32
    shuffle: false
    num_workers: 4
    repeat: 1
    mod: 1
  test:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    sample_stride: 64
    data_argumentation: false
    file_list: ./data/test_sisr.txt
    keep_full: true
    patch_size: [64, 64]
    batch_size: 32
    shuffle: false
    num_workers: 4
    repeat: 1
    mod: 1
  val_test:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    sample_stride: 64
    data_argumentation: false
    file_list: ./data/val_test_sisr.txt
    keep_full: true
    patch_size: [64, 64]
    batch_size: 32
    shuffle: false
    num_workers: 4
    repeat: 1
    mod: 1


