net:
  DBPN_3:
    scale_factor: 4
    num_channels: 3
    base_filter: 32
    feat: 64
    num_stages: 3
    residual: true
save_dir: ./output/dbpn_4x
trainer:
  SISRTrainer:
    epochs: 1000
    log_dir: logs
    ckpt_dir: ckpt
    log_frq: 10
    output_dir: eval
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.0001
scheduler:
  name: CosineAnnealingWarmRestarts
  steps:
data:
  name: SISRDataset
  train:
    image_dir: ./data
    upscale_factor: 4
    data_argumentation: true
    file_list: ./data/train_sisr.txt
    patch_size: [64, 64]
    batch_size: 48
    shuffle: true
    num_workers: 8
    repeat: 5
    mod: 1
  val:
    image_dir: ./data
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/val_sample_sisr.txt
    patch_size: [64, 64]
    batch_size: 48
    shuffle: false
    num_workers: 4
    repeat: 5
    mod: 1


