net:
  DBPN_3:
    scale_factor: 4
    num_channels: 3
    base_filter: 128
    feat: 96
    num_stages: 3
    residual: true
save_dir: ./output/dbpn_4x
trainer:
  SISRTrainer:
    epochs: 200
    log_dir: logs
    ckpt_dir: ckpt
    log_frq: 10
    output_dir: eval
    result_dir: ./output/dbpn_4x/06-01-00/eval
    restore_ckpt: ./output/dbpn_4x/06-01-00/ckpt/model-epoch134.pth.tar
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.0001
data:
  train:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    data_argumentation: true
    file_list: ./data/train_sisr.txt
    patch_size: [64, 64]
    batch_size: 20
    shuffle: true
    num_workers: 8
    repeat: 5
    mod: 1
  val:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/val_sisr.txt
    patch_size: [64, 64]
    batch_size: 20
    shuffle: false
    num_workers: 4
    repeat: 1
    mod: 1
  test:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    sample_stride: 64
    data_argumentation: false
    file_list: ./data/test_sisr.txt
    keep_full: true
    patch_size: [64, 64]
    batch_size: 20
    shuffle: false
    num_workers: 4
    repeat: 1
    mod: 1


