net:
  DBPN_3:
    scale_factor: 4
    num_channels: 1
    base_filter: 96
    feat: 96
    num_stages: 3
    residual: true
trainer:
  SISRTrainer:
    epochs: 100
    log_dir: logs
    ckpt_dir: ckpt
    log_frq: 10
    restore_ckpt: ckpt/model-best-pth.tar
    format: YCbCr
optimizer:
  name: Adam
  lr: 0.0004
  weight_decay: 0.0001
scheduler:
  name: MultiStepLR
  milestones: [30, 50]
data:
  train:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    data_argumentation: true
    file_list: ./data/train_sisr.txt
    patch_size: [64, 64]
    batch_size: 32
    shuffle: true
    num_workers: 8
    repeat: 5
    mod: 1
    format: YCbCr
  val:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/val_sisr.txt
    patch_size: [64, 64]
    batch_size: 32
    shuffle: false
    num_workers: 4
    repeat: 5
    mod: 1
    format: YCbCr
  test:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    sample_stride: 64
    data_argumentation: false
    file_list: ./data/test_sisr.txt
    keep_full: true
    patch_size: [64, 64]
    batch_size: 24
    shuffle: false
    num_workers: 4
    repeat: 1
    mod: 1
    format: YCbCr
  val_test:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    sample_stride: 64
    data_argumentation: false
    file_list: ./data/val_test_sisr.txt
    keep_full: true
    patch_size: [64, 64]
    batch_size: 24
    shuffle: false
    num_workers: 4
    repeat: 1
    mod: 1
    format: YCbCr



