net:
  DBPN_5:
    scale_factor: 4
    num_channels: 3
    base_filter: 96
    feat: 64
    num_stages: 5
    residual: true
save_dir: ./output/dbpn5_4x
trainer:
  SISRTrainer:
    epochs: 200
    log_dir: logs
    ckpt_dir: ckpt
    log_frq: 10
    output_dir: eval
    restore_dir: ./output/dbpn5_4x/05-31-01/ckpt/model-epoch67.pth.tar
    result_dir: ./output/dbpn5_4x/05-31-01/eval
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.0001
scheduler:
  name: none
data:
  train:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    data_argumentation: true
    file_list: ./data/train_sisr.txt
    patch_size: [64, 64]
    batch_size: 12
    shuffle: true
    num_workers: 8
    repeat: 5
    mod: 1
  val:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/val_sisr.txt
    patch_size: [64, 64]
    batch_size: 12
    shuffle: false
    num_workers: 4
    repeat: 1
    mod: 1
  test:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/test_sisr.txt
    sample_stride: 64
    patch_size: [64, 64]
    keep_full: true
    batch_size: 12
    shuffle: false
    num_workers: 4
    repeat: 1
    mod: 1


