net:
  EDSR:
    n_resblocks: 32
    n_feats: 256
    scale_factor: 2
    num_channels: 3
    res_scale: 0.1
trainer:
  SISRTrainer:
    epochs: 1000
    log_dir: logs
    ckpt_dir: ckpt
    log_frq: 10
    output_dir: ./output/edsr_2x/05-30-02/eval
    restore_ckpt: ./output/edsr_2x/05-30-02/ckpt/model-epoch112.pth.tar
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.0001
scheduler:
  name: none
data:
  name: SISRDataset
  test:
    image_dir: ./data
    upscale_factor: 2
    sample_stride: 64
    data_argumentation: false
    file_list: ./data/test_sisr.txt
    keep_full: true
    patch_size: [64, 64]
    batch_size: 16
    shuffle: false
    num_workers: 4
    repeat: 1
    mod: 1