net:
  EDSR:
    n_resblocks: 16
    n_feats: 64
    scale_factor: 2
    num_channels: 3
    res_scale: 1.0
trainer:
  SISRTrainer:
    epochs: 100
    log_dir: logs
    ckpt_dir: ckpt
    log_frq: 10
optimizer:
  name: Adam
  lr: 0.0004
  weight_decay: 0.0001
scheduler:
  name: MultiStepLR
  milestones: [30, 50]
data:
  train:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 2
    data_argumentation: true
    file_list: ./data/train_sisr.txt
    patch_size: [64, 64]
    batch_size: 48
    shuffle: true
    num_workers: 8
    repeat: 5
    mod: 1
  val:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 2
    data_argumentation: false
    file_list: ./data/val_sisr.txt
    patch_size: [64, 64]
    batch_size: 48
    shuffle: false
    num_workers: 4
    repeat: 5
    mod: 1
  test:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 2
    sample_stride: 64
    data_argumentation: false
    file_list: ./data/test_sisr.txt
    keep_full: true
    patch_size: [64, 64]
    batch_size: 48
    shuffle: false
    num_workers: 4
    repeat: 1
    mod: 1
  val_test:
    name: SISRDataset
    image_dir: ./data
    upscale_factor: 2
    sample_stride: 64
    data_argumentation: false
    file_list: ./data/val_test_sisr.txt
    keep_full: true
    patch_size: [64, 64]
    batch_size: 20
    shuffle: false
    num_workers: 4
    repeat: 1
    mod: 1