net:
  FRVSR:
    channel: 3
    gain: 10.0
    up_scale: 4
    n_rb: 16
    filter: 64
    flow_layer_num: 3
save_dir: ./output/frvsr
trainer:
  FRVSRTrainer:
    epochs: 200
    log_dir: logs
    ckpt_dir: ckpt
    log_frq: 10
    output_dir: eval
    flow_loss_weight: 1.0
    flow_var_weight: 0.001
    up_scale: 4
    result_dir: ./output/frvsr/06-01-07/eval
    restore_ckpt: ./output/dbpn_4x/06-01-07/ckpt/model-epoch197.pth.tar
optimizer:
  name: Adam
  lr: 0.0001
scheduler:
  name: none
data:
  train:
    name: VSRDataset
    image_dir: ./data
    window: 5
    stride: 2
    upscale_factor: 4
    data_argumentation: true
    file_list: ./data/train.txt
    patch_size: [64, 64]
    sample_strategy: random
    batch_size: 20
    shuffle: true
    num_workers: 4
    mod: 8
    repeat: 5
  val:
    name: VSRDataset
    image_dir: ./data
    window: 5
    stride: 2
    upscale_factor: 4
    data_argumentation: true
    file_list: ./data/val_sample.txt
    patch_size: [64, 64]
    sample_strategy: start
    batch_size: 20
    shuffle: false
    num_workers: 4
    mod: 8
    repeat: 5
  test:
    name: VSRTestDataset
    image_dir: ./data
    window: 5
    stride: 2
    sample_stride: 2
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/test_sisr.txt
    patch_size: [64, 64]
    sample_strategy: start
    batch_size: 20
    shuffle: false
    num_workers: 4
    mod: 8



