net:
  RBPNComposer:
    window: 5
    scale_factor: 4
    num_channels: 3
    base_filter: 64
    feat: 64
    num_stages: 3
    n_resblock: 5
    residual: true
    gain: 10
    f: 16
    flow_layer_num: 3
    res_scale: 0.1
save_dir: ./output/rbpn_composer
trainer:
  RBPNComposerTrainer:
    epochs: 200
    log_dir: logs
    ckpt_dir: ckpt
    log_frq: 10
    output_dir: eval
    up_scale: 4
    result_dir: ./output/rbpn_composer/06-04-01/eval2
    restore_ckpt: ./output/rbpn_composer/06-04-01/ckpt/model-best-pth.tar
    flow_loss_weight: 0.05
    tv_loss_weight: 0.00001
optimizer:
  name: Adam
  lr: 0.0001
scheduler:
  name: none
data:
  train:
    name: VSRDataset
    image_dir: ./data
    window: 5
    stride: 1
    upscale_factor: 4
    data_argumentation: true
    file_list: ./data/train.txt
    patch_size: [64, 64]
    sample_strategy: random
    batch_size: 4
    shuffle: true
    num_workers: 4
    mod: 8
    repeat: 5
  val:
    name: VSRDataset
    image_dir: ./data
    window: 5
    stride: 1
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/val.txt
    patch_size: [64, 64]
    sample_strategy: start
    batch_size: 4
    shuffle: false
    num_workers: 4
    mod: 8
    repeat: 1
  test:
    name: VSRTestDataset
    image_dir: ./data
    window: 5
    stride: 1
    sample_stride: [64, 64]
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/test_sisr.txt
    patch_size: [64, 64]
    keep_full: true
    sample_strategy: center
    batch_size: 12
    shuffle: false
    num_workers: 4
    mod: 8
    repeat: 1



