net:
  RBPNComposer:
    window: 5
    scale_factor: 4
    num_channels: 3
    base_filter: 64
    feat: 64
    num_stages: 3
    n_resblock: 7
    residual: true
    gain: 32
    f: 16
    flow_layer_num: 2
save_dir: ./output/rbpn_composer
trainer:
  RBPNComposerTrainer:
    epochs: 50
    log_dir: logs
    ckpt_dir: ckpt
    log_frq: 10
    output_dir: eval
    up_scale: 4
    result_dir: ./output/dbpn_composer/06-01-07/eval
    restore_ckpt: ./output/dbpn_composer/06-01-07/ckpt/model-epoch197.pth.tar
    flow_loss_weight: 1.0
    tv_loss_weight: 0.0001
optimizer:
  name: Adam
  lr: 0.0001
scheduler:
  name: none
data:
  train:
    name: VSRDataset
    image_dir: ./data
    window: 5
    stride: 1
    upscale_factor: 4
    data_argumentation: true
    file_list: ./data/train.txt
    patch_size: [64, 64]
    sample_strategy: random
    batch_size: 2
    shuffle: true
    num_workers: 4
    mod: 8
    repeat: 5
  val:
    name: VSRDataset
    image_dir: ./data
    window: 5
    stride: 1
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/val_sample.txt
    patch_size: [64, 64]
    sample_strategy: start
    batch_size: 2
    shuffle: false
    num_workers: 4
    mod: 8
    repeat: 5
  test:
    name: VSRTestDataset
    image_dir: ./data
    window: 5
    stride: 1
    sample_stride: [64, 64]
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/test_sisr.txt
    patch_size: [64, 64]
    keep_full: true
    sample_strategy: end
    batch_size: 2
    shuffle: false
    num_workers: 4
    mod: 8



