net:
  RBPN:
    window: 3
    scale_factor: 4
    num_channels: 3
    base_filter: 64
    feat: 32
    num_stages: 2
    n_resblock: 2
    residual: false
save_dir: ./output/rbpn
trainer:
  RBPNTrainer:
    epochs: 50
    log_dir: logs
    ckpt_dir: ckpt
    log_frq: 10
    output_dir: eval
optimizer:
  name: Adam
  lr: 0.00001
scheduler:
  name: none
data:
  train:
    image_dir: ./data
    window: 3
    stride: 2
    sample_stride: 5
    upscale_factor: 4
    data_argumentation: true
    file_list: ./data/train.txt
    patch_size: 128
    future_frame: true
    sample_strategy: start
    batch_size: 4
    shuffle: true
    num_workers: 4
  val:
    image_dir: ./data
    window: 3
    stride: 2
    sample_stride: 5
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/val.txt
    patch_size: 128
    future_frame: true
    sample_strategy: start
    batch_size: 4
    shuffle: false
    num_workers: 4
  test:
    image_dir: ./data
    window: 3
    stride: 2
    sample_stride: 1
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/test.txt
    patch_size: 0
    future_frame: true
    sample_strategy: start
    batch_size: 1
    shuffle: false
    num_workers: 4



