net:
  RBPN:
    window: 3
    scale_factor: 4
    num_channels: 3
    base_filter: 64
    feat: 64
    num_stages: 3
    n_resblock: 7
    residual: true
save_dir: ./output/rbpn
trainer:
  RBPNTrainer:
    epochs: 50
    log_dir: logs
    ckpt_dir: ckpt
    log_frq: 10
    output_dir: eval
optimizer:
  name: Adam
  lr: 0.0001
scheduler:
  name: none
data:
  train:
    name: VSRFlowDataset
    image_dir: ./data
    window: 3
    stride: 2
    sample_stride: 5
    upscale_factor: 4
    data_argumentation: true
    file_list: ./data/train.txt
    patch_size: [64, 64]
    future_frame: true
    sample_strategy: random
    batch_size: 4
    shuffle: true
    num_workers: 4
    repeat: 10
  val:
    name: VSRFlowDataset
    image_dir: ./data
    window: 3
    stride: 2
    sample_stride: 5
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/val.txt
    patch_size: [64, 64]
    future_frame: true
    sample_strategy: start
    batch_size: 4
    shuffle: false
    num_workers: 4
    repeat: 1
  test:
    name: VSRFlowDataset
    image_dir: ./data
    window: 3
    stride: 2
    sample_stride: 1
    upscale_factor: 4
    data_argumentation: false
    file_list: ./data/test.txt
    patch_size: [64, 64]
    future_frame: true
    sample_strategy: start
    batch_size: 1
    shuffle: false
    num_workers: 4
    repeat: 1



